# Generated by Django 6.0.3 on 2026-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('output', models.ImageField(blank=True, null=True, upload_to='outputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
